---
- hosts: servers
  tasks:
    - name: Установка на CentOS
      yum:
        name: java-11-openjdk-devel
        state: latest
      when:
        ansible_distribution == "CentOS"
      become: yes
      become_method: sudo

    - name: Установка на Debian
      apt:
        name: openjdk-11-jdk
        state: latest
      when:
        ansible_distribution == "Debian"
      become: yes
      become_method: sudo

    - name: Копирование JAR на сервер
      copy:
        src: ../target/smart-home-1.0-SNAPSHOT.jar
        dest: /home/mftiedu/smart-home.jar

    - name: Запуск JAR
      shell: java -jar smart-home.jar
