---
- hosts: servers
  tasks:
    - name: Копирование JAR на сервер
      file:
        src: "{{ lookup('env', 'WORKSPACE') }}/target/smart-home-1.0-SNAPSHOT.jar"
        dest: /home/mftiedu/mitrokosta/smart-home.jar
